# Generated by Django 5.2.1 on 2026-03-16 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchreview',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.batch'),
        ),
        migrations.AddField(
            model_name='batchreview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.batch'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.batch'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livesession',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='courses.batch'),
        ),
        migrations.AddField(
            model_name='progress',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.content'),
        ),
        migrations.AddField(
            model_name='progress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_items', to='courses.enrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='batchreview',
            unique_together={('batch', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'batch')},
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('enrollment', 'content')},
        ),
    ]
