# Generated by Django 5.2.1 on 2026-03-16 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mental_health', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moodcheck',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='psychologistsession',
            name='psychologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psych_sessions_as_psychologist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='psychologistsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psych_sessions_as_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ventroommessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
