# Generated by Django 5.2.1 on 2026-03-16 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyproject',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='legacy.legacyproject'),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studenttutorial',
            name='enrolled_mentors',
            field=models.ManyToManyField(blank=True, related_name='reverse_tutorials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studenttutorial',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='projectsubmission',
            unique_together={('project', 'student')},
        ),
    ]
